/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedVerifyRouteImport } from './routes/_authenticated/verify'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedStudentsNewRouteImport } from './routes/_authenticated/students.new'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'

const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedVerifyRoute = AuthenticatedVerifyRouteImport.update({ id: '/verify', path: '/verify', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({ id: '/dashboard', path: '/dashboard', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({ id: '/students', path: '/students', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedStudentsNewRoute = AuthenticatedStudentsNewRouteImport.update({ id: '/students/new', path: '/students/new', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({ id: '/students/$id', path: '/students/$id', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({ id: '/logs', path: '/logs', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({ id: '/users', path: '/users', getParentRoute: () => AuthenticatedRoute } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({ id: '/settings', path: '/settings', getParentRoute: () => AuthenticatedRoute } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/verify': typeof AuthenticatedVerifyRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/students/new': typeof AuthenticatedStudentsNewRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRoutesByTo extends FileRoutesByFullPath {}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/verify': typeof AuthenticatedVerifyRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/students/new': typeof AuthenticatedStudentsNewRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/dashboard' | '/verify' | '/students' | '/students/new' | '/students/$id' | '/logs' | '/users' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/dashboard' | '/verify' | '/students' | '/students/new' | '/students/$id' | '/logs' | '/users' | '/settings'
  id: '__root__' | '/' | '/_authenticated' | '/login' | '/_authenticated/' | '/_authenticated/dashboard' | '/_authenticated/verify' | '/_authenticated/students' | '/_authenticated/students/new' | '/_authenticated/students/$id' | '/_authenticated/logs' | '/_authenticated/users' | '/_authenticated/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': { id: '/login'; path: '/login'; fullPath: '/login'; preLoaderRoute: typeof LoginRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated': { id: '/_authenticated'; path: ''; fullPath: ''; preLoaderRoute: typeof AuthenticatedRouteImport; parentRoute: typeof rootRouteImport }
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/_authenticated/': { id: '/_authenticated/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof AuthenticatedIndexRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/verify': { id: '/_authenticated/verify'; path: '/verify'; fullPath: '/verify'; preLoaderRoute: typeof AuthenticatedVerifyRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/dashboard': { id: '/_authenticated/dashboard'; path: '/dashboard'; fullPath: '/dashboard'; preLoaderRoute: typeof AuthenticatedDashboardRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/students': { id: '/_authenticated/students'; path: '/students'; fullPath: '/students'; preLoaderRoute: typeof AuthenticatedStudentsRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/students/new': { id: '/_authenticated/students/new'; path: '/students/new'; fullPath: '/students/new'; preLoaderRoute: typeof AuthenticatedStudentsNewRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/students/$id': { id: '/_authenticated/students/$id'; path: '/students/$id'; fullPath: '/students/$id'; preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/logs': { id: '/_authenticated/logs'; path: '/logs'; fullPath: '/logs'; preLoaderRoute: typeof AuthenticatedLogsRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/users': { id: '/_authenticated/users'; path: '/users'; fullPath: '/users'; preLoaderRoute: typeof AuthenticatedUsersRouteImport; parentRoute: typeof AuthenticatedRoute }
    '/_authenticated/settings': { id: '/_authenticated/settings'; path: '/settings'; fullPath: '/settings'; preLoaderRoute: typeof AuthenticatedSettingsRouteImport; parentRoute: typeof AuthenticatedRoute }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedVerifyRoute: typeof AuthenticatedVerifyRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedStudentsNewRoute: typeof AuthenticatedStudentsNewRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute,
  AuthenticatedDashboardRoute,
  AuthenticatedVerifyRoute,
  AuthenticatedStudentsRoute,
  AuthenticatedStudentsNewRoute,
  AuthenticatedStudentsIdRoute,
  AuthenticatedLogsRoute,
  AuthenticatedUsersRoute,
  AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(AuthenticatedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()
